### ISSUE TITLE
Integrate with ECOTOXr

### ISSUE THREAD

**Issue by pepijn-devries** [tsufz/REcoTox#24]
Hi Tobias,

Just came across your package.  It seems that you are working on processes that I intended to implement in the [ECOTOXr](https://github.com/pepijn-devries/ECOTOXr) package. That package downloads the ASCII tables from ECOTOX and builds a local SQLite database, which can then be queried. It only removes the most prominent errors in the ASCII files (required for building the database) but it does not do any further processing of the data. This was something I had planned for the future, but is something you have apparently been working on. Do you think it would be opportune to merge the packages, or should we continue developing as separate packages?

Cheers,

Pepijn

**Comment by tsufz** [comment]
Hi Pepijn,
I was not aware of your package. However, it is a good opportunity to merge the two packages. Joint efforts are better. I did not test your package, but I guess, it has some automatisation which I also have in mind. The licences do also fit. We need to agree on the name of the joint package. I would prefer REcoTox as we published already some papers citing this package. Another one is in review.

Looking forward to the co-operation!

Best,
Tobias

**Comment by pepijn-devries** [comment]
Glad to hear that you are positive towards co-operation. Naming the package is something we have to think about. As you might have guessed, I would prefer ECOTOXr, because it is already deployed on CRAN under that name and have also a manuscript on the package almost ready to submit.

Another option would be to merge them under a new name. In the mean time, we might consider including elements from each others package in current branches, as long as the licensing and credits are respected?

Kind regards,

Pepijn

**Comment by tsufz** [comment]
Okay, then let's keep in separated packages. Our approach is different, not querying single substances, but whole assessment. The licences fit, so no issues with reuse.

Best
Tobias

**Comment by pepijn-devries** [comment]
Hi Tobias,

Do you have plans to submit to CRAN? That would make it easier to import your pacakge and call relevant functions... I'll still keep integration in mind, maybe something for in the future...

Kind regards,

Pepijn

**Comment by tsufz** [comment]
Hi Pepijn,
I made no final decision. But this may help. I need to think about the export of the functions first. Plenty of other tasks on the pile.

Keep also in mind.

Best,
Tobias

**Comment by pepijn-devries** [comment]
Thanks. I will keep an eye on your progress. Let's stay in touch...
